{"name": "test_login[login1]", "status": "failed", "statusDetails": {"message": "AssertionError: 失败原因：账号不正确\nassert False", "trace": "self = <test_zxj.Homework.test_cal.TestLogin object at 0x00000213D6A2BB00>, login = False\n\n    def test_login(self,login):\n        a = login\n        print(\"返回值%s\",a)\n>       assert a,\"失败原因：账号不正确\"\nE       AssertionError: 失败原因：账号不正确\nE       assert False\n\ntest_cal.py:28: AssertionError"}, "attachments": [{"name": "stdout", "source": "65070bb5-ae2b-4cd6-86f6-ec960b9398b7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login", "value": "('zzz', 'jjj')"}], "start": 1594370341639, "stop": 1594370341640, "uuid": "e6f665b5-9e92-4fc4-b1b5-88cade67d723", "historyId": "934565262cd18427bbe2b8f3f61d696e", "testCaseId": "f53a883f3eec74aba65feaed76ab2c8a", "fullName": "test_cal.TestLogin#test_login", "labels": [{"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-G8ROBTKO"}, {"name": "thread", "value": "12440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cal"}]}